# Generated by Django 5.2.5 on 2025-08-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='gender',
            field=models.CharField(choices=[('M', 'Мальчик'), ('F', 'Девочка'), ('U', 'Не указано')], default='U', max_length=1),
        ),
    ]
