# Generated by Django 5.2.8 on 2025-11-10 03:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_alter_child_options_child_account_user_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Visit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recorded_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата посещения"
                    ),
                ),
                (
                    "child",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="visits",
                        to="core.child",
                        verbose_name="Ученик",
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="recorded_visits",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Отметил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Посещение",
                "verbose_name_plural": "Посещения",
                "ordering": ["-recorded_at"],
            },
        ),
    ]
